Added Jira contribution to Task_Management_Software.md
learning-software-engineering/learning-software-engineering.github.io pull request #153
Opened 2023-11-22 04:38 UTC by jenniferxi

Added the following sections:
1. Getting started with Jira
2. Core features of Jira
3. Best practices for task management
4. Useful resources

2023-11-27 15:34 UTC, celinayueh requested changes
Hi Jennifer, thank you for giving a in-depth introduction of Jira along with several ways to integrate it into a work process. I can see many future 301 teams finding this useful for managing their tasks.

While your descriptions are very helpful, I think it would be useful to add some links to more documentation or examples for some sections so users can see working examples of the features being described, notably sections 2a, b, and 3a.

I noticed you had some sections like 3a and 3b that had a short summary or short best practice blurb which improves the flow of your entry - maybe you can add it to some other sections as well? 

Great job!

2023-11-28 22:07 UTC, jenniferxi commented
Hi Celina, thank you so much for taking the time to review the Jira documentation!

I appreciate your suggestion about adding links to documentation or examples in the specified sections. I completely agree, and I'll find and incorporate relevant links to provide users with examples for a more hands-on experience.

Additionally, your comment about the short summaries in sections 3a and 3b enhancing the flow is insightful. I'll certainly add this to improve the flow and structure throughout the entry.

Thanks again for your feedback and positive remarks! I'll add these improvements promptly.

2023-11-28 22:14 UTC, jenniferxi commented
Revised Task_Management_Software.md
Added links to relevant documentation to specified sections
Added best practices blurbs at the end of sections

2023-11-29 01:41 UTC, celinayueh approved these changes

2023-11-29 16:49 UTC, merged