Addition of 'Asynchronous External API Interface in a Python Application' tutorial
learning-software-engineering/learning-software-engineering.github.io pull request #210
Opened 2023-11-27 02:50 UTC by AlmostGreenz

Addition of this new tutorial for implementing an Asynchronous External API interface using Python. 

This tutorial gives an overview of APIs and asynchronous programming before delving into progressively more developed examples of an Asynchronous API interface that would be well-suited for a Python application like a web server.

Please let me know if you have any suggestions for improvements that could be made.

2023-11-27 20:15 UTC, Leuxll requested changes
Overall good work! I just made a few comments for your consideration.

2023-11-28 22:02 UTC, AlmostGreenz commented on Topics/Tech_Stacks/Async_External_API_Interface_Python.md
> +Now, let's adapt this example to be asynchronous using `httpx` and `asyncio`. Before we proceed, again please ensure you have installed the `httpx` library for Python:
asyncio is a Python built-in library, but you're right that it's not clear. I'm going to clarify that in this section to save any confusion, thanks!

2023-11-28 22:29 UTC, AlmostGreenz commented on Topics/Tech_Stacks/Async_External_API_Interface_Python.md
> +## What does 'Asynchronous' mean?
Good suggestion - I'd mentioned a web server here, but I've just expanded that into a full explanation and comparison.

2023-11-28 22:52 UTC, AlmostGreenz commented on Topics/Tech_Stacks/Async_External_API_Interface_Python.md
> +Once the response is returned, it is determined whether the connection was a success and a boolean is returned whether it was or was not based on the status code. Otherwise, an error must be raised w
Good catch - I've just added a new section about it!

2023-11-28 23:00 UTC, AlmostGreenz commented on Topics/Tech_Stacks/Async_External_API_Interface_Python.md
> +data = response.json()
I've just added a discussion about it and I'm going to push my changes now

2023-11-29 02:21 UTC, Leuxll approved these changes
Just took a look at all the changes, everything looks good to me!

2023-11-29 02:22 UTC, merged