Added salesforce_api.md in Teck_Stacks
learning-software-engineering/learning-software-engineering.github.io pull request #47
Opened 2023-03-20 13:27 UTC by CorinneLS

2023-03-21 06:34 UTC, SanjanaGirish approved these changes
Excellent work. The topic is very well explained with reference to documentation and images. Adding image references at the end was a nice touch. A short and thorough contribution.

2023-03-21 06:34 UTC, SanjanaGirish commented on Topics/Tech_Stacks.md
> +### [How to access and use salesforce API](./Tech_Stacks/salesforce_api.md)
Creating a new file and adding content is a nice idea to avoid merge conflicts.

2023-03-21 16:25 UTC, SanjanaGirish requested changes
Please resolve conflicts and update Readme accordingly.

2023-03-21 16:36 UTC, CorinneLS commented
Conflicts have been resolved

2023-03-21 17:14 UTC, merged

2023-03-21 17:15 UTC, SanjanaGirish commented
Please update Readme as well.

2023-03-22 15:45 UTC, CorinneLS commented
I've updated the Readme, pls see the new pull request