Added entry for Creational Design Patterns
learning-software-engineering/learning-software-engineering.github.io pull request #503
Opened 2024-03-17 17:09 UTC by ChowdhuryShaswata

- Added a markdown file detailing the 5 most commonly used creational design patterns, including the usage, structure and benefits of each.
- Added self-created UML diagrams expressing the structure of these design patterns.
- Added links to further resources.

2024-03-17 17:43 UTC, paridhi26 requested changes
Good job explaining different creational design patterns! The usage of UML diagrams is very helpful. The document flows well and is easy to read. I have suggested some formatting improvements and additions that can further improve the readability of the document in the comments :)

2024-03-17 17:43 UTC, paridhi26 commented on Topics/System_Design/DesignPatterns/Creational_Design_Patterns.md
> +
As a suggestion, adding a conclusion section summarizing each of the design patterns and comparing/contrasting them for particular scenarios that arise when programming would be a good wrap-up.

2024-03-17 17:43 UTC, paridhi26 commented on Topics/System_Design/DesignPatterns/Creational_Design_Patterns.md
> +Refactoring Guru provides a detailed reference guide with examples for creational design patterns, as well as other design patterns that can be useful to implement in the right scenarios.
Good job including extra resources. These links are helpful!

2024-03-17 17:43 UTC, paridhi26 commented on Topics/System_Design/DesignPatterns/Creational_Design_Patterns.md
> +A singleton achieves 2 purposes: it maintains exactly 1 instance of a given class  across the entire program, and it provides a global access point to that class. It achieves this by first hiding the
Converting the 2 purposes into a list of bullet points may improve readability.

2024-03-17 17:43 UTC, paridhi26 commented on Topics/System_Design/DesignPatterns/Creational_Design_Patterns.md
> +
Great job including the UML diagrams. Very instructive.

2024-03-17 17:43 UTC, paridhi26 commented on Topics/System_Design/DesignPatterns/Creational_Design_Patterns.md
> +
Optionally, I think adding short examples for each design pattern to illustrate what scenarios they could be used in could be a good addition! 

For example: When programming functionality for a bakery, a Simple Factory design pattern can be used to create different types of pastries such as croissants, muffins, and cookies. The factory takes input from customers (e.g., pastry type) and produces the corresponding pastry without exposing the complexities of the baking process.

2024-03-17 17:43 UTC, paridhi26 commented on Topics/System_Design/DesignPatterns/Creational_Design_Patterns.md
> +
Adding a table of contents for easy navigation and overview of content on this page could be a good addition.

2024-03-18 00:24 UTC, Aiforall123 requested changes
Excellent Shaswata! UML diagrams are very good and the explanation for each design pattern is good. Just try to add a table of content and conclusion :)

2024-03-18 00:24 UTC, Aiforall123 commented on Topics/System_Design/DesignPatterns/Creational_Design_Patterns.md
> +# Creational Design Patterns
I would try to add a table of content which would be good to jump from section to section.

2024-03-18 01:45 UTC, Aiforall123 requested changes
Excellent Shaswata for adding the Conclusion and Table of Content. However, I cannot see the image being appeared correctly.

2024-03-18 01:57 UTC, paridhi26 approved these changes
Great job adding the table of contents and examples! The document is now easier to navigate thanks to the table of contents and the examples make the design patterns must easier to understand.

2024-03-18 01:59 UTC, Aiforall123 approved these changes
All the conflicts are now resolved and the images are appearing correctly. Ready to merge.

2024-03-18 02:08 UTC, merged