Create logging_to_mysql.md
learning-software-engineering/learning-software-engineering.github.io pull request #535
Opened 2024-03-17 21:42 UTC by hantien2002

2024-03-17 22:53 UTC, Tahasp commented
Hey, would you be up to reviewing each other’s work?

2024-03-17 23:29 UTC, hantien2002 commented
@Tahasp Hi, sorry I have already found teammate to review my work.

2024-03-18 00:31 UTC, OliviaYZhou commented
Hi Tien, the PR looks good overall, I like the visuals and images you included, especially the video. 
One thing you could add is you can explain your logs table in Step 2. For instance, the user might not know what a level is or why it needs to be added. You have a pretty good explanation for users table in part 3, maybe you can do something similar for logs table.
On a similar note, since you are adding a users table, but not all logging requires a user, you can add a section explaining a use case where someone would need a users table, and explain that this tutorial will be most helpful in similar cases.

2024-03-18 00:37 UTC, OliviaYZhou requested changes
Sorry I commented in wrong place. This is the PR review.

Hi Tien, the PR looks good overall, I like the visuals and images you included, especially the video.
One thing you could add is you can explain your logs table in Step 2. For instance, the user might not know what a level is or why it needs to be added. You have a pretty good explanation for users table in part 3, maybe you can do something similar for logs table.
On a similar note, since you are adding a users table, but not all logging requires a user, you can add a section explaining a use case where someone would need a users table, and explain that this tutorial will be most helpful in similar cases.

2024-03-18 00:40 UTC, OliviaYZhou requested changes

2024-03-18 00:40 UTC, OliviaYZhou commented on Topics/Software_Engineering/logging_to_mysql.md
> +
You can add an explanation for the columns here

2024-03-18 00:40 UTC, OliviaYZhou commented on Topics/Software_Engineering/logging_to_mysql.md
> +
Maybe add a use case for an app that would require logging and also has a users table around here

2024-03-18 01:36 UTC, hantien2002 commented
@OliviaYZhou Hi Olivia, thank you for your review and I have made changes based on your suggestion.

2024-03-18 02:01 UTC, merged

2024-03-18 02:05 UTC, OliviaYZhou commented
Hi Tien, I've seen the changes and they look great. The explanations make the tutorial clearer. This will be a great guide for anyone who wants to create logging using mysql.