Added TypeScript.md in Tech_Stacks
learning-software-engineering/learning-software-engineering.github.io pull request #55
Opened 2023-03-21 00:03 UTC by MehrdadQ

Added TypeScript.md in Tech_Stacks, and updated Tech_Stacks.md to include the new addition

2023-03-22 04:42 UTC, lmg8 requested changes
This is a good introduction to typescript with plenty of helpful resources. I would consider adding a table of contents similar to [MySQL page](https://github.com/learning-software-engineering/learning-software-engineering.github.io/blob/main/Topics/Tech_Stacks/Learning_MySQL.md) or [swift](https://github.com/learning-software-engineering/learning-software-engineering.github.io/blob/main/Topics/Tech_Stacks/swift.md) to make it more consistent with other tech stack pages.

Also, may you fix the merge conflicts in Tech_Stacks.md

2023-03-22 04:42 UTC, lmg8 commented on Topics/Tech_Stacks/TypeScript.md
> +You can find the complete guide [here](https://create-react-app.dev/docs/adding-typescript/). To learn more about React and TypeScript,You can also follow [this YouTube video by Ben Awad](https://www
```suggestion
You can find the complete guide [here](https://create-react-app.dev/docs/adding-typescript/). To learn more about React and TypeScript, you can also follow [this YouTube video by Ben Awad](https://www.youtube.com/watch?v=Z5iWr6Srsj8&t=28s&ab_channel=BenAwad).
```

2023-03-22 23:06 UTC, lmg8 approved these changes

2023-03-22 23:11 UTC, lmg8 requested changes
One small thing: can you update the readme.md so future contributors know where to update Typescript related resources?

2023-03-22 23:57 UTC, MehrdadQ commented
so just add it to the main readme like that? please let me know if there is anything else

2023-03-23 00:01 UTC, lmg8 approved these changes

2023-03-23 00:01 UTC, merged